name: Deploy to self-hosted debin
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: mvn --batch-mode clean package

      - name: Start service
        run: |
          sudo systemctl stop grande.service
          sudo mv target/grande.jar /app/grande.jar
          sudo systemctl start grande.service